# Generated by Django 4.1.7 on 2023-03-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanalservis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='cost_in_rubles',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='description',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
